/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://g3qoseczgfgqlbpalmvzisip4e.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7juiai3t5bei5myz6gtp6vwjci",
    "aws_cognito_identity_pool_id": "us-east-2:a4e60046-faca-4d20-81ba-e179a75f0ae0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PHNR2jDDf",
    "aws_user_pools_web_client_id": "78q0caqr9rv0qcmurik3r92nm0",
    "oauth": {}
};


export default awsmobile;
